// <auto-generated />
namespace MyTrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedForms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedForms));
        
        string IMigrationMetadata.Id
        {
            get { return "201703032218316_AddedForms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
